[package]
name = "chibi-datalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datalog-syntax = { path = "datalog-syntax" }
datalog_rule_macro = { path = "datalog_rule_macro" }
crepe = "0.1.8"
lasso = { version = "0.7.2", features = ["ahash"] }
regex = "1.0"
indexmap = { version = "2.1.0" }
rkyv = { version = "0.7.42", features = ["validation"] }
dbsp = "0.2.0"
size-of = "0.1.5"
phf = { version = "0.11", features = ["macros"] }
clap = "3.1.1"