[package]
name = "chibi-datalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datalog_syntax = { path = "datalog_syntax" }
datalog_rule_macro = { path = "datalog_rule_macro" }
lasso = { version = "0.7.2", features = ["ahash"] }
indexmap = { version = "2.1.0" }
rkyv = { version = "0.7.42", features = ["validation"] }
dbsp = "0.2.0"
size-of = "0.1.5"
ahash = "0.8.11"
dyn-hash = "0.2.0"