[package]
name = "datalog_syntax_macros"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Two procedural macros to easily write datalog programs and rules"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"